model: yolov5x-cls.pt
data: /root/autodl-tmp/garbage265
epochs: 80
batch_size: 128
imgsz: 448
nosave: false
cache: null
device: '0'
workers: 8
project: yolov5/runs/train-cls
name: garbage265_hierarchical
exist_ok: true
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
nc_major: 4
major_weight: 0.5
val_period: 5
save_dir: yolov5/runs/train-cls/garbage265_hierarchical
